### ISSUE TITLE
Problem with FreSharp If I upgrade to Net Frameworks 4.6.1 and Adobe Air SDK 24.0

### ISSUE THREAD

**Issue by ghost** [tuarua/FreSharp#1]
Hello dear Tuana!

I have managed your FreSharp and FreSharpCore in Visual Studio 2017 Community and I have upgraded than I change both dlls from FreSharp and FreSharpCore FreSharpExampleAne(+lib) And I have changed sources because I wish I have tried. But no success for Adobe Air.
And I have completed successful complications than I merge Flash Builder 4.6 with Adobe Air SDK 24.0

And I add native extension to my example air application. But Adobe Air always freeze. I tried to export to native installer and no success. Why does it happen? Is it bug because AS3-reference ExtensionContext doesn't answer, right? - But I didn't mess up with FreSharp.

How is your work around with Adobe Air SDK 19.0? Does it work while ExtensionContext answers? If you open Air Application and Air Application doesn't freeze.

I'm sorry for bad English. Thanks!

**Comment by tuarua** [comment]
> But Adobe Air always freeze.

What do you mean freeze? Is there an error? Does the app crash when you build ?
When these dlls are compiled did you copy them into the bin folder of AIRSDK ?
FreSharp.dll 
FreSharpCore.dll 
FreSharpExampleANELib.dll 

Please provide screenshots of errors so I can understand better

**Comment by tuarua** [comment]
I see you posted a youtube video on AIR forum.
I will have a look and get back to you

**Comment by tuarua** [comment]
these C# dll files should sit in same folder as your exe.
(And in the same folder as adl.exe for debugging)
FreSharp.dll
FreSharpCore.dll
**FreSharpExampleANELib.dll**

the ANE should only include the C++ dll
FreSharpExampleANE.dll

I couldn't see **FreSharpExampleANELib.dll** in your video. I think you forgot to copy that one.

**Comment by ghost** [comment]
Thanks for explanation! I am sorry for that. I have resolved it. I think sure for packing native installer with loaded dlls. You're right

**Comment by tuarua** [comment]
Yes please use a native installer to pack the dlls, check dependencies etc.
Hope you build something great !!

Quick question. I see you are using VS 2017.
Can you compile dlls that are msvc14.0 aka 2015 ??

I would like to upgrade VS but want to keep my ANEs compatible with 2015 C++ runtime.

**Comment by ghost** [comment]
Correct, ( Haha! ) I know now how do I pack with important dlls like same WebviewANE too.
But it looks like crazy. PS: Why not use BoxedApp Packer or Engima VirtualBox after installed / unpacked Air application content. If you have error message like Adobe Air need install.

1. Create project without ane - Don't worry for that my great magic. 
Other easy empty project: Just same details name of xml. than you generate air-captive than

2. Download and install/unpack resource hacker
Generated air app exe  -> resource hacker and generated by native installer exe -> resource hacker - If you see like both sometimes same identifiers
Find:  5 identifiers from generated air app exe copy all identiefer and past to air-captive app exe ( old same identiefers should remove ). and air captive exe need save and build ( like Play symbol ) than 
Locale to Adobe Air/Version/1.0/ and remove "Resources" and go back and copy Adobe AIr and air-captived exe to generated air application's content and check to open if dlls from extension still are working on air captive exe. Yay! And remove generated air app exe and rename air-captived exe to same generated exe's filename.
Than you can wish if you want pack into standalone executable or let content if you like that?

Yes, I am using Visual Studio 2017 Community. No problem it can works fine with msvc150.0.
If yo want stay current version than I make for Visual Studio 2017.  I have installed same Visual Studio 2015 and It can works with msvc14.0 too But solution file after saving was updated to Visual Studio 2017 Community.

Thanks for resolving!

**Comment by tuarua** [comment]
Do these tools check the user has the required runtimes such as .NET MSVC, C++ distro etc ??
I use IntelliJ and it creates a single exe package no problem.
The problem comes when a user doesn't have for eg .NET 4.5 +
I worked with InnoSetup years ago and you can build an installer script which will check for .NET etc.

Thanks,
I will check out 2017

**Comment by ghost** [comment]
![embed_fresharp_into_standalone](https://cloud.githubusercontent.com/assets/3496136/25544696/e7cc9d88-2c5b-11e7-8b84-2d3b1b316748.JPG)

It is easy no problem with Air Captive app. magic was released from Russian guy - he explained me about resource hacker because template and I have downloaded and unpacked zipped file. I am surprised because he doesn't have generated native installer and he generated air-captive runtime and hacks line from resource hacker with air captive exe makes alive with nativeprocess and extensions.

And it is great solution about embedded air applications 

// EDIT you said correct. I wish I try if dlls should generate from net core 1.0.1 like publish to content of exe without any installed net frameworks. I saw news

You're welcome :)
