### ISSUE TITLE
[Question] What sort of mid-long term support will this project have?

### ISSUE THREAD

**Issue by TranzRail** [tuarua/FreSharp#16]
Looks great, thinking of using it in some projects. Curious to know if this is developed purely for fun/personal projects or is being used on something bigger.

Cheers.

**Comment by tuarua** [comment]
Hi,
This library is used in this project which is used by many people in commercial projects.
https://github.com/tuarua/WebViewANE

Version 2.0 of FreSharp will be out soon which adds a few tweaks, additional methods & syntactic sugars.

**Comment by TranzRail** [comment]
That's great to hear. Wish I found this before I learned to do it the hard way. What sort of licence does it have?

**Comment by tuarua** [comment]
Apache 2.0 - so free to use for commercial or personal projects.
I think some people had created C# based ANEs before but this library is the first to provide a proper C# wrapper for FlashRuntimeExtensions. 
I have a Swift one too which is architecturally similar.
