### ISSUE TITLE
Step by step guide

### ISSUE THREAD

**Issue by TommyTheBlackbird** [tuarua/FreSharp#7]
Is it posible to have a step by step guide for building an ANE from scratch? I'm trying to write my first Extension but just looking at the example I can't figure out how to glue all the pieces and which are needed  for a new extension or are just part of the example.

Regards.

**Comment by tuarua** [comment]
It's fair to say that the example is really more of a test bed.
I will look into putting together a short video on creating a simple Hello World from scratch.
I am doing similar for FreSwift at the moment as its example is also a little unclear.

**Comment by tuarua** [comment]
Please see the starter project.
It is the most minimal example.
Use this as a starting point.

https://github.com/tuarua/FreSharp/tree/master/starter_project

**Comment by TommyTheBlackbird** [comment]
Thanks a lot for the effort. I'll take a look ASAP.

**Comment by TommyTheBlackbird** [comment]
Pretty much clear now! Thanks. 👍
