### ISSUE TITLE
AIR application crash: System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by TommyTheBlackbird** [tuarua/FreSharp#8]
I'm not sure if this FreSharp issue or just a common one with ANE developement.

When I run my app it crashes. Looking at the windows event log I get this:
```
Application: CarteleriaApp.exe
Framework version: v4.0.30319
Description:  Unhandled exception.
Exception information: System.IO.FileNotFoundException
   at <Module>.FreSharpBridge.InitController()
   at <Module>.CDIPB_contextInitializer(Void*, Byte*, Void*, UInt32*, FRENamedFunction_**)
```
("CDIPB" is my chosen identifier)

I have successfully run the ANE launching it from Flash CC Professional (I guess because all dll's are copied at the AIR_SDK\bin from build-windows.bat), but when I install and run the application it crashes.

My app is installed with the native installer created with ```adt -target native```. The application with the extension seems to be installed ok, as all needed files are at the folder
```
C:\Program Files (x86)\MyCompany\MyApp\META-INF\AIR\extensions\es.telecor.vt.cdi.bridge.PlayerBridgeExtension\Meta-Inf\ane\Windows-x86\
--- FreSharp.dll
--- FreSharpCore.dll
--- library.swc
--- PlayerBridgeANE.dll (my C++ FreSharp wrapper)
--- PlayerBridgeANELib.dll (my C# Main controller)
```
The error stack suggests that the main C++ DLL is loaded ok because the context initializer is invoked but not the C# library. Maybe the additional libs have to be somewhere else, but the extension dir seems the right place to me...

EDIT:
I've get the windows dump file and it confirm that de PlayerBridgeANE.dll (the C++ one) is loaded but not PlayerBridgeANELib.dll (C#). Also debugging the crash with Visual Studio, it stops at FREBRIDGE_INIT macro with 
```
Unhandled exception type 'System.IO.FileNotFoundException' at PlayerBridgeANE.dll.
Unable to load the file or assembly 'PlayerBridgeANELib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' 
or one of its dependencies.  The system can not find the specified file.
```

**Comment by TommyTheBlackbird** [comment]
It seems to work fine when I move any DLLs other than the C++ extension to the .exe folder instead of the extension directory. I'll have to figure out if a can put this files here with the AIR native installer instead of creating an extra installer but it's not a FreSharp issue.

**Comment by TommyTheBlackbird** [comment]
Just FYI, dlls seems to be loaded when the any class using the ANE class is invoked so it's possible to add some code before it, at the application start, to copy or move them from other location (like the app-resources folder) to the application .exe folder where you can add files to the application package. I tried it and seems to work fine.

**Comment by tuarua** [comment]
you could also try using SetDllDirectory early in the c++ code, to add a search path.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms686203(v=vs.85).aspx

The page also outlines details Windows uses as the search order.
It is standard to have dlls parrallel to main exe in apps for this reason so I didn't add anything else. This project started out when I was implementing Cefsharp and it has many dlls and they must be placed in root.
