### ISSUE TITLE
Add call to ContextFinalizer in c# lib

### ISSUE THREAD

**Issue by TommyTheBlackbird** [tuarua/FreSharp#9]
I've implemented a call to a method in the C# lib from the C++ ContextFinalizer function in my ANE project because I need to dispose some resources when closing the app.

I think it would be a good idea to have this as a built-in feature in other to allow the C# lib to free resources (files, listeners, connections, process hooks or whatever....).

**Comment by tuarua** [comment]
I too add a dispose function in the ContextFinalizer.
I have some small tweaks planned and one of them is to use an Interface for the C# MainController which specifies default methods/props.
I will add some kind of "Dispose()" method which can be overridden

**Comment by tuarua** [comment]
This has been added in latest version.
There are some other changes, see starter_project
